### ISSUE TITLE
Sharing library with the interface  between service and  unity client?

### ISSUE THREAD

**Issue by feritzcan2** [Cysharp/MagicOnion#512]
Hello, we are using magiconion for our game. Our client is unity and server is .net6.  We want to share our common project which includes Service and Hub interfaces between server and client.

We dont want to create both files on two sides nor do copy and paste. I'm trying to publish class library that holds interfaces and references package MagicOnion.Abstractions into nuget and use it in unity..

However, MagicOnion.Abstractions have references to Grpc.Core.Api and MesagePack which yields our package to automatically install those referenced packages. Since, implementation(library) of grpc in unity is different and manually installed, We cant do it safely.

Is there any way to achieve this?

**Comment by Danila24ru** [comment]
Line 8
https://github.com/Cysharp/MagicOnion/blob/master/samples/ChatApp/ChatApp.Shared/ChatApp.Shared.csproj
Or you can build DLL and copy it to unity project "AfterBuild" target.

**Comment by feritzcan2** [comment]
@Danila24ru 
Hi Daniala, thank you for your answer.

However, code below would work only in the same repository. We have seperate repositories for server and unity so that we cant share files across solutions.
  <ItemGroup>
    <Compile Include="..\ChatApp.Unity\Assets\Scripts\ServerShared\**\*.cs" />
  </ItemGroup>


Also, I thought dll would work but I face same problems with nuget ( error below) . Dlls dont recognize magiconion package that is included in unity. When I pack my library nuget using PrivateAssets="All" flag (ignore dependencies in nuget transition)
I got same error.  Somehow, I should find a way to add reference to local magiconnion libraries for dlls.



: The type 'IService<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'MagicOnion.Abstractions, Version=4.4.0.0, Culture=neutral, PublicKeyToken=7bf5b512f16761c0'.

**Comment by Danila24ru** [comment]
Try to disable AutoReference inside your dll in unity. 

Also we use server/unity inside same repository + symLinks.
Repository
-| Project.Unity
-| Project.Server
-| .gitignore
If you use docker to build server. It also will give you ability to access Unity folder.

**Comment by feritzcan2** [comment]
@Danila24ru 
It didnt work, If below is what you meant.. Thank you anyway :(
![image](https://user-images.githubusercontent.com/55948243/161263002-69725eb0-6371-4c36-b1ba-c2a8ed1fbc87.png)

**Comment by Danila24ru** [comment]
Oh sorry, i messed up. I meant Validate References.

**Comment by feritzcan2** [comment]
@Danila24ru  This doesnt work for service project dll that references MagicOnion.Abstractions  :(. However, it works for common entity project that involves MessagePackObjects( project we had the same reference issues but includes messagepack dependency in stead of magic onion)

**Comment by feritzcan2** [comment]
For those who are trying to do this... Just use submodules in github.

**Comment by mwegner** [comment]
Unity really likes to own the files.  I set up a project so that:

* The single copy of the file lives in the Unity folder
* There is a standalone .csproj that includes these files
* Other, non-Unity projects reference this project

In the .csproj it's something like:

```
<ItemGroup>
    <Compile Include="..\..\Unity_Project\Assets\_Scripts\Core\*.cs" Link="Core\%(FileName)%(Extension)" />
    <Compile Include="..\..\Unity_Project\Assets\_Scripts\Core\**\*.cs" Link="Core\%(RecursiveDir)%(FileName)%(Extension)" />
</ItemGroup>
```

There are other examples here of linking like this.  I found it easier to link into a "real" .csproj and then use that onwards, rather than each project including the files iteslf.  We have a couple of projects that reference this embedding project--the actual MagicOnion server, but also some CLI benchmarks and tests.

The Unity project has its own copy of MagicOnion (and MessagePack).  The non-Unity projects just use matching versions via NuGet.

For us, we have quite a lot of code that lives in the non-Unity portion, but this could also narrowly target just the interfaces and network implementation.  Personally, I use a single file for a hub or receiver, with defines splitting the client/server implementation.

Hope this helps!  Git submodules have a lot of friction.  From one Internet stranger to another, I think you'll be better off in the long term by referencing files directly in the `.csproj` like this...
