### ISSUE TITLE
Idea: Underlying gRPC transport over Shared Memory

### ISSUE THREAD

**Issue by loligans** [Cysharp/MagicOnion#539]
In an attempt to get ever better performance I wanted to ask if it would be possible to implement some form of Shared Memory for the underlying gRPC connection. Considering there is support already for SignalR and even Named Pipes at first glance it seems possible.

The thought is to utilize something similar to Microsoft.IO.RecyclableMemoryStream to act as the supportive structure for data transport.

I don't know how realistic or practical this is but I really like MagicOnion and I suspect if something like this could work it could significantly increase throughput.

**Comment by mayuki** [comment]
Since MagicOnion implements gRPC (Grpc.Net) on top, it is possible to change the gRPC transport.
For example, gRPC over Unix domain sockets is supported by ASP.NET Core and SocketsHttpHandler.
https://docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-6.0

In other words, it would be possible to achieve the same thing on shared memory, but it seems pretty difficult.
MagicOnion server built on ASP.NET Core, so it would be very hard to implement Kestrel transport.

**Comment by loligans** [comment]
I see, so MagicOnion uses the gRPC transport mechanism provided by Kestrel and any implementation using Shared Memory would have to be done there.
